# Generated by Django 5.1.11 on 2026-05-27 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phno', models.CharField(max_length=12)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('bloodgroup', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_proof', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('candidate_photo', models.FileField(blank=True, null=True, upload_to='candidate_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_enroll', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'REGISTRATION',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_of_payment', models.CharField(default='Razorpay', max_length=50)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registration')),
            ],
            options={
                'db_table': 'PAYMENT',
            },
        ),
    ]
