# Generated by Django 5.1.11 on 2026-05-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(default='Razorpay', max_length=50)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PAYMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(db_column='Registration_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('phno', models.CharField(db_column='Phno', max_length=12)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('bloodgroup', models.CharField(blank=True, db_column='Bloodgroup', max_length=50, null=True)),
                ('identity_proof', models.FileField(blank=True, db_column='identity_proof', max_length=255, null=True, upload_to='identity_proofs/')),
                ('candidate_photo', models.FileField(blank=True, db_column='candidate_photo', max_length=255, null=True, upload_to='candidate_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('competition_name', models.CharField(blank=True, db_column='Competition_name', max_length=100, null=True)),
                ('type_of_enroll', models.CharField(blank=True, db_column='Type_of_Enroll', max_length=100, null=True)),
            ],
            options={
                'db_table': 'REGISTRATION',
                'managed': False,
            },
        ),
    ]
